spring:
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
    h2:
        console:
            path: /h2-console
            enabled: true
            settings:
                trace: true
    datasource:
        url: jdbc:h2:mem:localtest
        driverClassName: org.h2.Driver
        username: sa
        generate-unique-name: false
    cloud:
        config:
            enabled: false
        discovery:
            client:
                simple:
                    instances:
                        portone:
                            -   serviceId: portone
                                instanceId: portone1
                                uri: https://api.iamport.kr

